name: Build and Push Docker Image (On Demand with Version + Latest)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read version from package.json
        id: version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker images (version + latest)
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/my-plex-bot:${{ steps.version.outputs.VERSION }} \
                       -t ghcr.io/${{ github.repository_owner }}/my-plex-bot:latest .

      - name: Push Docker images
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/my-plex-bot:${{ steps.version.outputs.VERSION }}
          docker push ghcr.io/${{ github.repository_owner }}/my-plex-bot:latest
